"""update user admin table to Boolean

Revision ID: 75605f469203
Revises: 656e5128a20e
Create Date: 2023-05-18 07:46:29.918174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75605f469203'
down_revision = '656e5128a20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
